export const LINE_LIST_COLUMNS = [
  { key: 'circuitName', label: 'Circuit Name', required: true, type: 'string' },
  { key: 'segmentName', label: 'Segment Name', required: false, type: 'string' },
  { key: 'lineNumber', label: 'Line Number', required: true, type: 'string' },
  { key: 'tempControlType', label: 'Temp. Control Type', required: true, type: 'lookup', lookupKey: 'tempControlType' },
  { key: 'maintTemp', label: 'Maint. Temp.', required: true, type: 'number' },
  { key: 'minAmbientTemp', label: 'Min. Ambient Temp.', required: true, type: 'number' },
  { key: 'startUpAmbient', label: 'Start Up Ambient', required: false, type: 'number' },
  { key: 'wind', label: 'Wind', required: false, type: 'number' },
  { key: 'safetyFactor', label: 'Safety Factor', required: false, type: 'number' },
  { key: 'circuitConfiguration', label: 'Circuit Configuration', required: true, type: 'lookup', lookupKey: 'circuitConfiguration' },
  { key: 'volts', label: 'Volts', required: true, type: 'lookup', lookupKey: 'volts' },
  { key: 'breakerSize', label: 'Breaker Size', required: false, type: 'number' },
  { key: 'breakerType', label: 'Breaker Type', required: false, type: 'lookup', lookupKey: 'breakerType' },
  { key: 'pipeSize', label: 'Pipe Size', required: true, type: 'string' },
  { key: 'pipeLen', label: 'Pipe Len.', required: true, type: 'number' },
  { key: 'maxExpTemp', label: 'Max. Exp. Temp.', required: false, type: 'number' },
  { key: 'maxProductTemp', label: 'Max. Product Temp.', required: false, type: 'number' },
  { key: 'modNo', label: 'Mod. No.', required: false, type: 'string' },
  { key: 'workPackageNo', label: 'Work Package No.', required: false, type: 'string' },
  { key: 'areaNo', label: 'Area No.', required: false, type: 'string' },
  { key: 'pipeMaterial', label: "Pipe Mat'l.", required: true, type: 'lookup', lookupKey: 'pipeMaterial' },
  { key: 'insulType', label: 'Insul. Type', required: true, type: 'lookup', lookupKey: 'insulType' },
  { key: 'insulThk', label: 'Insul. Thk', required: true, type: 'string' },
  { key: 'insulSizing', label: 'Insul Sizing', required: false, type: 'lookup', lookupKey: 'insulSizing' },
  { key: 'heaterStyle', label: 'Heater Style', required: true, type: 'lookup', lookupKey: 'heaterStyle' },
  { key: 'heaterFamily', label: 'Heater Family', required: false, type: 'lookup', lookupKey: 'heaterFamily' },
  { key: 'class', label: 'Class', required: false, type: 'lookup', lookupKey: 'hazClass' },
  { key: 'divZone', label: 'Div/Zone', required: false, type: 'lookup', lookupKey: 'divZone' },
  { key: 'group', label: 'Group', required: false, type: 'lookup', lookupKey: 'group' },
  { key: 'tClass', label: 'T-Class', required: false, type: 'lookup', lookupKey: 'tClass' },
  { key: 'ait', label: 'AIT', required: false, type: 'number' },
  { key: 'additionalCable', label: 'Additional Cable for Field Variance', required: false, type: 'number' },
];