// Sample line list rows for demo/testing (simulates parsed Excel data)
export const SAMPLE_ROWS = [
  {
    circuitName: 'HT-001', segmentName: 'SEG-A', lineNumber: 'L-100-01-XXXX',
    tempControlType: 'Self-Regulating', maintTemp: 50, minAmbientTemp: -20, startUpAmbient: -30,
    wind: 15, safetyFactor: 1.1, circuitConfiguration: 'Parallel', volts: '120',
    breakerSize: 20, breakerType: 'GFEP', pipeSize: '2"', pipeLen: 45, maxExpTemp: 65,
    maxProductTemp: 75, modNo: 'M-01', workPackageNo: 'WP-100', areaNo: 'A1',
    pipeMaterial: 'Carbon Steel', insulType: 'Mineral Wool', insulThk: '1.5"',
    insulSizing: 'OD', heaterStyle: 'Parallel', heaterFamily: 'XL-Trace',
    class: 'I', divZone: 'Division 2', group: 'D', tClass: 'T3', ait: 250, additionalCable: 3,
  },
  {
    circuitName: 'HT-002', segmentName: 'SEG-A', lineNumber: 'L-100-02-XXXX',
    tempControlType: 'Constant Watt', maintTemp: 60, minAmbientTemp: -20, startUpAmbient: -25,
    wind: 15, safetyFactor: 1.15, circuitConfiguration: 'Series', volts: '240',
    breakerSize: 15, breakerType: 'GFEP+OL', pipeSize: '3"', pipeLen: 78, maxExpTemp: 75,
    maxProductTemp: 85, modNo: 'M-01', workPackageNo: 'WP-100', areaNo: 'A1',
    pipeMaterial: 'Stainless Steel', insulType: 'Calcium Silicate', insulThk: '2"',
    insulSizing: 'OD', heaterStyle: 'Parallel', heaterFamily: 'BTV',
    class: 'I', divZone: 'Division 1', group: 'C', tClass: 'T2', ait: 300, additionalCable: 5,
  },
  {
    circuitName: 'HT-003', segmentName: 'SEG-B', lineNumber: 'L-200-01-XXXX',
    tempControlType: 'Self-Regulating', maintTemp: 45, minAmbientTemp: -30, startUpAmbient: -35,
    wind: 20, safetyFactor: 1.2, circuitConfiguration: 'Parallel', volts: '480',
    breakerSize: 30, breakerType: 'Standard', pipeSize: '6"', pipeLen: 120, maxExpTemp: 60,
    maxProductTemp: 70, modNo: 'M-02', workPackageNo: 'WP-200', areaNo: 'B2',
    pipeMaterial: 'Carbon Steel', insulType: 'Fiberglass', insulThk: '1"',
    insulSizing: 'ID', heaterStyle: 'Parallel', heaterFamily: 'QTVR',
    class: 'II', divZone: 'Division 2', group: 'E', tClass: 'T4', ait: 180, additionalCable: 0,
  },
  {
    circuitName: 'HT-004', segmentName: 'SEG-B', lineNumber: 'L-200-02-XXXX',
    tempControlType: 'Mineral Insulated', maintTemp: 120, minAmbientTemp: -20, startUpAmbient: -20,
    wind: 10, safetyFactor: 1.25, circuitConfiguration: 'Series', volts: '600',
    breakerSize: 40, breakerType: 'EPD', pipeSize: '4"', pipeLen: 55, maxExpTemp: 150,
    maxProductTemp: 200, modNo: 'M-02', workPackageNo: 'WP-200', areaNo: 'B2',
    pipeMaterial: 'Alloy Steel', insulType: 'Calcium Silicate', insulThk: '2.5"',
    insulSizing: 'OD', heaterStyle: 'Series', heaterFamily: 'MI',
    class: 'I', divZone: 'Zone 1', group: 'IIB', tClass: 'T5', ait: 400, additionalCable: 8,
  },
  {
    circuitName: 'HT-005', segmentName: 'SEG-C', lineNumber: 'L-300-01-XXXX',
    tempControlType: 'Self-Regulating', maintTemp: 35, minAmbientTemp: -15, startUpAmbient: -20,
    wind: 10, safetyFactor: 1.1, circuitConfiguration: 'Parallel', volts: '120',
    breakerSize: 20, breakerType: 'GFEP', pipeSize: '1"', pipeLen: 22, maxExpTemp: 55,
    maxProductTemp: 65, modNo: 'M-03', workPackageNo: 'WP-300', areaNo: 'C1',
    pipeMaterial: 'Carbon Steel', insulType: 'Polyurethane Foam', insulThk: '1"',
    insulSizing: 'OD', heaterStyle: 'Parallel', heaterFamily: 'XSR',
    class: 'I', divZone: 'Division 2', group: 'D', tClass: 'T3', ait: 250, additionalCable: 2,
  },
];